dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: treasury-db
  version: 0.1.0
  repository: http://chartmuseum.fr1cslfcglo0082.misys.global.ad
  alias: kplus-db
- name: kondor-front-internal
  version: 348.0.131-201907060517.1357.e24e818
  repository: http://chartmuseum.fr1cslfcglo0082.misys.global.ad
- name: treasury
  version: 4.0.0-20190707T082108.sha8a29e00.252
  repository: http://chartmuseum.fr1cslfcglo0082.misys.global.ad
